"use client";

import { useState, useCallback, useMemo } from "react";
import { Copy, Check, Plus, Trash2, Download } from "lucide-react";
import { trackToolEvent } from "@/lib/analytics";

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }, [text]);
  return (
    <button onClick={handleCopy} disabled={!text}
      className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg border border-gray-200 hover:border-blue-400 hover:bg-blue-50 disabled:opacity-40 transition-all">
      {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
      {copied ? "Copied!" : "Copy"}
    </button>
  );
}

interface Rule {
  type: "Allow" | "Disallow";
  path: string;
}

interface AgentBlock {
  userAgent: string;
  crawlDelay: string;
  rules: Rule[];
}

const COMMON_PATHS = [
  "/admin/",
  "/private/",
  "/tmp/",
  "/cgi-bin/",
  "/wp-admin/",
  "/wp-login.php",
  "/search",
  "/api/",
  "/*.pdf$",
  "/*.json$",
];

const COMMON_AGENTS = [
  "*",
  "Googlebot",
  "Bingbot",
  "Baiduspider",
  "YandexBot",
  "DuckDuckBot",
  "Slurp",
  "facebookexternalhit",
  "Twitterbot",
  "GPTBot",
  "CCBot",
  "ChatGPT-User",
  "anthropic-ai",
  "ClaudeBot",
];

export default function RobotsGeneratorClient() {
  const [blocks, setBlocks] = useState<AgentBlock[]>([
    { userAgent: "*", crawlDelay: "", rules: [{ type: "Allow", path: "/" }] },
  ]);
  const [sitemaps, setSitemaps] = useState<string[]>([""]);

  const addBlock = () => {
    setBlocks([...blocks, { userAgent: "Googlebot", crawlDelay: "", rules: [{ type: "Allow", path: "/" }] }]);
  };

  const removeBlock = (i: number) => {
    if (blocks.length > 1) setBlocks(blocks.filter((_, idx) => idx !== i));
  };

  const updateBlock = (i: number, field: "userAgent" | "crawlDelay", value: string) => {
    const updated = [...blocks];
    updated[i] = { ...updated[i], [field]: value };
    setBlocks(updated);
  };

  const addRule = (blockIdx: number) => {
    const updated = [...blocks];
    updated[blockIdx].rules.push({ type: "Disallow", path: "" });
    setBlocks(updated);
  };

  const removeRule = (blockIdx: number, ruleIdx: number) => {
    const updated = [...blocks];
    updated[blockIdx].rules = updated[blockIdx].rules.filter((_, i) => i !== ruleIdx);
    setBlocks(updated);
  };

  const updateRule = (blockIdx: number, ruleIdx: number, field: "type" | "path", value: string) => {
    const updated = [...blocks];
    const rules = [...updated[blockIdx].rules];
    rules[ruleIdx] = { ...rules[ruleIdx], [field]: value } as Rule;
    updated[blockIdx] = { ...updated[blockIdx], rules };
    setBlocks(updated);
  };

  const addSitemap = () => setSitemaps([...sitemaps, ""]);
  const removeSitemap = (i: number) => setSitemaps(sitemaps.filter((_, idx) => idx !== i));
  const updateSitemap = (i: number, value: string) => {
    const updated = [...sitemaps];
    updated[i] = value;
    setSitemaps(updated);
  };

  const output = useMemo(() => {
    const lines: string[] = [];
    lines.push("# robots.txt generated by FreeAIKit.app");
    lines.push("");

    for (const block of blocks) {
      lines.push(`User-agent: ${block.userAgent}`);
      if (block.crawlDelay) lines.push(`Crawl-delay: ${block.crawlDelay}`);
      for (const rule of block.rules) {
        if (rule.path) lines.push(`${rule.type}: ${rule.path}`);
      }
      lines.push("");
    }

    for (const sitemap of sitemaps) {
      if (sitemap.trim()) lines.push(`Sitemap: ${sitemap.trim()}`);
    }

    return lines.join("\n").trim();
  }, [blocks, sitemaps]);

  const handleDownload = useCallback(() => {
    trackToolEvent('robots-generator', 'download');
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
  }, [output]);

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Config */}
        <div className="space-y-4">
          {/* Agent blocks */}
          {blocks.map((block, bi) => (
            <div key={bi} className="bg-white rounded-2xl border border-gray-200 p-5 space-y-3">
              <div className="flex items-center justify-between">
                <h2 className="text-sm font-semibold text-gray-700">Agent Rule #{bi + 1}</h2>
                {blocks.length > 1 && (
                  <button onClick={() => removeBlock(bi)} className="text-gray-400 hover:text-red-500">
                    <Trash2 className="w-4 h-4" />
                  </button>
                )}
              </div>

              {/* User-agent */}
              <div>
                <label className="text-xs font-semibold text-gray-600 block mb-1">User-agent</label>
                <select value={block.userAgent} onChange={(e) => updateBlock(bi, "userAgent", e.target.value)}
                  className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">
                  {COMMON_AGENTS.map((a) => (
                    <option key={a} value={a}>{a === "*" ? "* (All bots)" : a}</option>
                  ))}
                </select>
              </div>

              {/* Crawl delay */}
              <div>
                <label className="text-xs font-semibold text-gray-600 block mb-1">Crawl Delay (seconds, optional)</label>
                <input type="number" value={block.crawlDelay} onChange={(e) => updateBlock(bi, "crawlDelay", e.target.value)}
                  placeholder="e.g. 10" min="0"
                  className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
              </div>

              {/* Rules */}
              <div className="space-y-2">
                <label className="text-xs font-semibold text-gray-600 block">Rules</label>
                {block.rules.map((rule, ri) => (
                  <div key={ri} className="flex items-center gap-2">
                    <select value={rule.type} onChange={(e) => updateRule(bi, ri, "type", e.target.value)}
                      className="px-2 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 w-28">
                      <option value="Allow">Allow</option>
                      <option value="Disallow">Disallow</option>
                    </select>
                    <div className="flex-1 relative">
                      <input value={rule.path} onChange={(e) => updateRule(bi, ri, "path", e.target.value)}
                        placeholder="/path/"
                        className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500" />
                    </div>
                    {block.rules.length > 1 && (
                      <button onClick={() => removeRule(bi, ri)} className="text-gray-400 hover:text-red-500 shrink-0">
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    )}
                  </div>
                ))}
                <div className="flex items-center gap-2">
                  <button onClick={() => addRule(bi)}
                    className="inline-flex items-center gap-1 px-2 py-1 text-xs font-semibold text-blue-600 hover:bg-blue-50 rounded-lg transition-colors">
                    <Plus className="w-3 h-3" /> Add Rule
                  </button>
                  <div className="text-xs text-gray-400">|</div>
                  <div className="flex flex-wrap gap-1">
                    {COMMON_PATHS.slice(0, 5).map((p) => (
                      <button key={p} onClick={() => {
                        const updated = [...blocks];
                        updated[bi].rules.push({ type: "Disallow", path: p });
                        setBlocks(updated);
                      }}
                        className="px-2 py-0.5 text-[10px] font-mono text-gray-500 bg-gray-50 rounded hover:bg-gray-100 transition-colors">
                        {p}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))}

          <button onClick={addBlock}
            className="w-full py-2.5 border-2 border-dashed border-gray-200 rounded-2xl text-sm font-semibold text-gray-500 hover:border-blue-300 hover:text-blue-600 transition-colors flex items-center justify-center gap-1.5">
            <Plus className="w-4 h-4" /> Add Another Agent Block
          </button>

          {/* Sitemaps */}
          <div className="bg-white rounded-2xl border border-gray-200 p-5 space-y-3">
            <h2 className="text-sm font-semibold text-gray-700">Sitemap URLs</h2>
            {sitemaps.map((s, i) => (
              <div key={i} className="flex items-center gap-2">
                <input value={s} onChange={(e) => updateSitemap(i, e.target.value)}
                  placeholder="https://example.com/sitemap.xml" type="url"
                  className="flex-1 px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                {sitemaps.length > 1 && (
                  <button onClick={() => removeSitemap(i)} className="text-gray-400 hover:text-red-500">
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            ))}
            <button onClick={addSitemap}
              className="inline-flex items-center gap-1 px-2 py-1 text-xs font-semibold text-blue-600 hover:bg-blue-50 rounded-lg transition-colors">
              <Plus className="w-3 h-3" /> Add Sitemap
            </button>
          </div>
        </div>

        {/* Right: Output */}
        <div className="space-y-4">
          <div className="bg-white rounded-2xl border border-gray-200 p-5 space-y-3 sticky top-20">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-semibold text-gray-700">robots.txt Output</h2>
              <div className="flex gap-2">
                <button onClick={handleDownload}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg border border-gray-200 hover:border-blue-400 hover:bg-blue-50 transition-all">
                  <Download className="w-3.5 h-3.5" /> Download
                </button>
                <CopyButton text={output} />
              </div>
            </div>
            <pre className="px-4 py-3 bg-gray-50 rounded-xl font-mono text-sm text-gray-700 overflow-auto max-h-[500px] whitespace-pre">{output}</pre>
            <p className="text-xs text-gray-400">
              Upload this file to the root of your website at <code className="bg-gray-100 px-1 rounded">example.com/robots.txt</code>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
