import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import ToolJsonLd from "../components/ToolJsonLd";

export const metadata: Metadata = {
  title: "Free Online Design Tools - QR Codes, Colors, Favicons | FreeAIKit",
  description:
    "Free design tools online: generate QR codes, extract color palettes, convert colors between HEX/RGB/HSL, create favicons, pick colors, and make memes. All browser-based, no signup required.",
  alternates: {
    canonical: "https://freeaikit.app/design-tools",
  },
};

const tools = [
  {
    slug: "qr-code",
    name: "QR Code Generator",
    description:
      "Generate QR codes for URLs, WiFi, email, and more. Customize colors, download PNG or SVG.",
  },
  {
    slug: "color-palette",
    name: "Color Palette Extractor",
    description:
      "Extract dominant color palettes from any image. Get hex codes and copy as CSS variables.",
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description:
      "Convert colors between HEX, RGB, HSL, and CMYK formats instantly. Live preview included.",
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description:
      "Generate favicons for all platforms from any image: 16×16, 32×32, 180×180, 192×192, 512×512.",
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description:
      "Pick colors from a visual palette and get HEX, RGB, HSL, CMYK values instantly.",
  },
  {
    slug: "meme-generator",
    name: "Meme Generator",
    description:
      "Create memes with custom top and bottom text. Upload any image, customize fonts and styles.",
  },
];

const faqItems = [
  {
    question: "What design tools does FreeAIKit offer?",
    answer:
      "FreeAIKit provides six free design tools: a QR Code Generator with customizable colors and SVG/PNG export, a Color Palette Extractor that pulls dominant colors from any image, a Color Converter for HEX/RGB/HSL/CMYK formats, a Favicon Generator for all platform sizes, a Color Picker with live preview, and a Meme Generator for creating image macros with custom text.",
  },
  {
    question: "Do these design tools require signup or payment?",
    answer:
      "No. Every design tool on FreeAIKit is completely free with no account registration, no email required, and no usage limits. All processing happens directly in your browser — your files never leave your device.",
  },
  {
    question: "Can I use the generated assets commercially?",
    answer:
      "Yes. QR codes, favicons, color palettes, and all other outputs generated by FreeAIKit tools are yours to use however you like, including commercial projects. There are no watermarks or licensing restrictions on the output.",
  },
  {
    question: "What image formats are supported?",
    answer:
      "Most design tools support JPG, PNG, and WebP input. The QR Code Generator outputs both PNG and SVG formats. The Favicon Generator creates ICO, PNG, and Apple Touch Icon formats for all major platforms and devices.",
  },
];

export default function DesignToolsPage() {
  return (
    <>
      <ToolJsonLd
        name="Free Online Design Tools"
        description="Free browser-based design tools: QR code generator, color palette extractor, color converter, favicon generator, color picker, and meme generator."
        slug="design-tools"
        faqItems={faqItems}
        itemListItems={tools.map((t, i) => ({
          position: i + 1,
          name: t.name,
          url: `https://freeaikit.app/${t.slug}`,
        }))}
      />

      <main className="min-h-screen bg-gray-50">
        {/* Hero */}
        <section className="bg-gradient-to-b from-gray-900 to-gray-800 text-white py-16 sm:py-24">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center">
            <h1 className="text-4xl sm:text-5xl font-bold mb-6">
              Free Online Design Tools
            </h1>
            <p className="text-lg text-gray-300 leading-relaxed max-w-3xl mx-auto">
              Great design starts with the right utilities. FreeAIKit gives
              designers, developers, and content creators a complete set of
              browser-based design tools that run entirely on your device.
              Generate customizable QR codes with your brand colors and download
              as crisp SVG or PNG files. Extract dominant color palettes from
              any photograph or screenshot to build cohesive design systems.
              Convert colors instantly between HEX, RGB, HSL, and CMYK formats
              with live previews. Create pixel-perfect favicons for every
              platform — from 16×16 browser tabs to 512×512 PWA icons — in a
              single click. Pick precise colors with an intuitive visual
              interface. Even create memes with custom text overlays for social
              media content. Every tool works instantly in your browser with
              zero signup, zero file uploads, and zero cost.
            </p>
          </div>
        </section>

        {/* Tool Cards */}
        <section className="max-w-5xl mx-auto px-4 sm:px-6 py-16">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {tools.map((tool) => (
              <Link
                key={tool.slug}
                href={`/${tool.slug}`}
                className="group bg-white rounded-2xl border border-gray-200 p-6 hover:border-blue-600 hover:shadow-lg transition-all duration-200"
              >
                <h2 className="text-xl font-semibold text-gray-900 mb-2 group-hover:text-blue-600 transition-colors">
                  {tool.name}
                </h2>
                <p className="text-gray-600 text-sm leading-relaxed mb-4">
                  {tool.description}
                </p>
                <span className="inline-flex items-center text-blue-600 text-sm font-medium">
                  Try it free
                  <ArrowRight className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform" />
                </span>
              </Link>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section className="max-w-3xl mx-auto px-4 sm:px-6 pb-20">
          <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 text-center mb-10">
            Frequently Asked Questions
          </h2>
          <div className="space-y-6">
            {faqItems.map((item, index) => (
              <div
                key={index}
                className="bg-white rounded-2xl border border-gray-200 p-6"
              >
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  {item.question}
                </h3>
                <p className="text-gray-600 leading-relaxed">{item.answer}</p>
              </div>
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
