"""
FreeAIKit Growth Engine — Feishu (飞书) Notification

Reads the daily opportunity report and sends Top 20 to Feishu group via webhook.

Usage:
    python feishu_notify.py [--date 2026-03-19]

Environment:
    FEISHU_WEBHOOK_URL — Feishu bot webhook URL (required)
"""

import json
import os
import sys
import urllib.request
from datetime import datetime, timezone

from config import DATA_DIR


def send_feishu_message(webhook_url, content):
    """Send a message to Feishu group via webhook."""
    payload = {
        "msg_type": "interactive",
        "card": content,
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        webhook_url,
        data=data,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            if result.get("code") == 0:
                print("Feishu notification sent successfully!")
            else:
                print(f"Feishu notification failed: {result}")
    except Exception as e:
        print(f"Error sending Feishu notification: {e}")


def build_card(opportunities, date_str, stats):
    """Build Feishu interactive card message."""
    # Build opportunity list text
    opp_lines = []
    for i, opp in enumerate(opportunities[:20], 1):
        score = "BREAKOUT" if opp.get("trend_score", 0) == 99999 else str(opp.get("combined_score", opp.get("trend_score", 0)))
        sources = " + ".join(opp.get("sources", ["unknown"]))
        opp_lines.append(f"**{i}.** {opp['keyword']}  (score: {score}, {sources})")

    opp_text = "\n".join(opp_lines) if opp_lines else "No new opportunities found today."

    card = {
        "config": {"wide_screen_mode": True},
        "header": {
            "title": {
                "tag": "plain_text",
                "content": f"🔍 FreeAIKit Keyword Report — {date_str}",
            },
            "template": "blue",
        },
        "elements": [
            {
                "tag": "div",
                "text": {
                    "tag": "lark_md",
                    "content": (
                        f"**Trends Rising:** {stats.get('trends_total', 'N/A')} keywords\n"
                        f"**Suggest Found:** {stats.get('suggest_total', 'N/A')} keywords\n"
                        f"**New Opportunities:** {len(opportunities)}"
                    ),
                },
            },
            {"tag": "hr"},
            {
                "tag": "div",
                "text": {
                    "tag": "lark_md",
                    "content": f"**Top 20 New Opportunities:**\n\n{opp_text}",
                },
            },
            {"tag": "hr"},
            {
                "tag": "note",
                "elements": [
                    {
                        "tag": "plain_text",
                        "content": "Auto-generated by FreeAIKit Growth Engine | GitHub Actions",
                    }
                ],
            },
        ],
    }
    return card


def main():
    # Check webhook URL
    webhook_url = os.environ.get("FEISHU_WEBHOOK_URL", "")
    if not webhook_url:
        print("ERROR: FEISHU_WEBHOOK_URL environment variable not set")
        print("Set it with: export FEISHU_WEBHOOK_URL='https://open.feishu.cn/open-apis/bot/v2/hook/xxx'")
        sys.exit(1)

    # Determine date
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    for i, arg in enumerate(sys.argv):
        if arg == "--date" and i + 1 < len(sys.argv):
            date_str = sys.argv[i + 1]

    # Load report
    report_path = os.path.join(DATA_DIR, f"report_{date_str}.json")
    if not os.path.exists(report_path):
        print(f"Report not found: {report_path}")
        print("Run report_generator.py first.")
        sys.exit(1)

    with open(report_path, "r", encoding="utf-8") as f:
        report = json.load(f)

    opportunities = report.get("top_50", [])[:20]
    stats = report.get("stats", {})

    # Build and send card
    card = build_card(opportunities, date_str, stats)
    send_feishu_message(webhook_url, card)


if __name__ == "__main__":
    main()
